### PR TITLE
Feat/authentication

### PR DESCRIPTION
**Pull request by manish591**
Features Added In This PR:
* Added login and logout functionality
* Added not found (404) page route
* Added basic routing for auth pages

`Note:` You can avoid reviewing CSS files.

### CODE REVIEW

**Review by romabulani — APPROVED** [review]
Very clean code. Learnt that
- we can pass "*" to Route for Error Handling
- use of useLocation to navigate the user to the previous page

**Review by shrey27 — APPROVED** [review]
Code looks good to merge.
Suggestion: Save all the end points in common file, so that they can be edited at one place in future

**Comment by manish591** [comment]
> Very clean code. Learnt that
> 
> * we can pass "*" to Route for Error Handling
> * use of useLocation to navigate the user to the previous page

Thanks

**Comment by manish591** [comment]
> Code looks good to merge. Suggestion: Save all the end points in common file, so that they can be edited at one place in future

Thanks for reviewing

**Pull request merged**
